.\"
.\" lftp.1 - Sophisticated ftp program
.\"
.\" This file is part of lftp.
.\"
.\" This program is free software; you can redistribute it and/or modify
.\" it under the terms of the GNU General Public License as published by
.\" the Free Software Foundation; either version 2 of the License , or
.\" (at your option) any later version.
.\"
.\" This program is distributed in the hope that it will be useful,
.\" but WITHOUT ANY WARRANTY; without even the implied warranty of
.\" MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
.\" GNU General Public License for more details.
.\"
.\" You should have received a copy of the GNU General Public License
.\" along with this program; see the file COPYING.  If not, write to
.\" the Free Software Foundation, 675 Mass Ave, Cambridge, MA 02139, USA.
.\"
.\" $Id$
.\"
.\"-------
.\" Sp	space down the interparagraph distance
.\"-------
.de Sp
.sp \\n(Ddu
..
.\"-------
.\" Ds	begin a display, indented .5 inches from the surrounding text.
.\"
.\" Note that uses of Ds and De may NOT be nested.
.\"-------
.de Ds
.Sp
.in +0.5i
.nf
..
.\"-------
.\" De	end a display (no trailing vertical spacing)
.\"-------
.de De
.fi
.in
..
.TH lftp 1 "19 Sep 1999"
.SH NAME
lftp \- Sophisticated ftp program
.SH SYNTAX
.B lftp
[\fB\-d\fR] [\fB\-e \fIcmd\fR] [\fB\-p \fIport\fR]
[\fB\-u \fIuser\fR[\fB,\fIpass\fR]] [\fIsite\fR]
.br
.B lftp \-f
.I script_file
.br
.B lftp \-c
.I commands
.br
.B lftp \-\-version
.br
.B lftp \-\-help

.SH VERSION
This man page documents lftp version 2.1.0.

.SH "DESCRIPTION"
\fBlftp\fR is a program that allows sophisticated ftp connection to
other hosts. If \fIhost\fR is specified then lftp will connect to that
host otherwise a connection has to be established with the open
command.
.PP
\fBlftp\fR is quite a powerful ftp client. It uses GNU readline to
read commands. It uses shell-like command syntax allowing you to
launch several commands in parallel in the background (&).
.PP
Some commands (cat, ls, site, quote) allow redirection of their output
to a file or via a pipe to external command. Commands can be started
conditionally based on termination status of previous command (&&,
||). Also, it is possible to group commands within () and execute them
in the background. All background jobs are executed in the same single
process. You can send a foreground job to the background with ^Z (C-z)
and back with the command `wait'.
.PP
When you think you are done but some background jobs are not yet finished,
you can just exit and lftp will move itself to nohup mode in
background and continue transfers. Records about moving to background
and termination of backgrounded precesses are logged in \fI~/.lftp/log\fP file,
along with other messages from backgrounded processes.
.PP
\fBlftp\fR has reliable put, reput, and mirror, along with many other
commands.
.PP
\fBlftp\fR does reconnect and reget automatically when the
connection broke and there is something to do.
.PP
Since version 2.0.0 lftp can handle three file access methods -
ftp, http and file. You can specify method to use in ``open URL'' command,
e.g. ``open http://www.us.kernel.org/pub/linux''.

.SS Commands
.PP

.BI ! " shell command"
.PP
Launch shell or shell command.
.PP
.Ds
!ls
.De
.PP
To do a directory listing of the local host.

.B alias
.RI " [" name " [" value ]]
.PP
Define or undefine alias \fIname\fP. If \fIvalue\fP is omitted, the alias is
undefined, else it takes the value \fIvalue\fP. If no argument is given
the current aliases are listed.
.PP
.Ds
alias dir ls -lF
alias less zmore
.De

.B anon
.PP
Sets the user to anonymous.  This is the default.

.BR at " \fItime\fP [ -- \fIcommand\fP ] "
.PP
Wait until the given time and execute given (optional) command. See also at(1).

.B bookmark
.RI " [" subcommand ]
.PP
The bookmark command controls bookmarks.
.Ds
  add <name> [<loc>] - add current place or given location
                       to bookmarks and bind to given name
  del <name>         - remove bookmark with name
  edit               - start editor on bookmarks file
  import <type>      - import foreign bookmarks
  list               - list bookmarks (default)
.De

.B cache
.RI " [" subcommand ]
.PP
The cache command controls local memory cache.
The following subcommands are recognized:
.TP
  stat      - print cache status (default)
.TP
  on|off    - turn on/off caching
.TP
  flush     - flush cache
.TP
  size \fIlim\fP  - set memory limit, -1 means unlimited
.TP
  expire \fINx\fP - set cache expiration time to \fIN\fP seconds (\fIx\fP=s)
         minutes (\fIx\fP=m) hours (\fIx\fP=h) or days (\fIx\fP=d)
.PP

.BR cat " [" -u ] " \fIfiles\fP"
.PP
cat outputs the remote file(s) to stdout.  (See also \fBmore\fR,
\fBzcat\fR and \fBzmore\fR)

.BR cd " rdir"
.PP
Change current remote directory.  The previous remote directory is
stored as `-'. You can do `cd -' to change the directory back.
The previous directory for each site is also stored on disk,
so you can do `open site; cd -' even after lftp restart.

.BR chmod " \fImode files\fP"
.PP
Change permission mask on remote files. The mode must be an octal number.

.BR close " [" -a "]"
.PP
Close idle connections.  By default only with the current server, use
-a to close all idle connections.

.BR command " \fIcmd args...\fP
.PP
execute given command ignoring aliases.

.BR debug " [" -o
.IR file "] "  level "|\fBoff\fP"
.PP
Switch debugging to \fIlevel\fP or turn it off.  Use -o to redirect
the debug output to a file.

.BR echo " [" -n "] \fIstring\fR"
.PP
guess what it does.

.BR exit " code"
.PP
exit will exit from lftp or move to background if jobs are active.  If
no jobs are active, \fIcode\fP is passed to operating system as lftp's
termination status. If \fIcode\fP is omitted, the exit code of last
command is used.

.B fg
.PP
Alias for `wait'.

.B find
.RI " [" directory "] "
.PP
List files in the directory (current directory by default) recursively.
This can help with servers lacking ls -R support. You can redirect output
of this command.

.BR ftpcopy " [" -p  "] [" -c "] \fIURL1 URL2\fR "
.PP
Copies URL1 to URL2 using special feature of ftp protocol, bypassing current
machine. If URL2 terminates with slash (/), then it is treated as directory,
and file name from URL1 is appended. By default, source server is used in
active mode, and target one in passive. Option -p reverses that. Option -c
requests continuation of transfer.

.BR get " [" -e "] [" -u "]"
.RB [ -c "] \fIrfile\fP [" -o " \fIlfile\fP]"
.PP
Retrieve the remote file \fIrfile\fP and store it as the local file
\fIlfile\fP.  If -o is omitted, the file is stored to local file named as
basename of \fIrfile\fP. If the option [-c] is specified, try to reget
specified files.  You can get multiple files by specifying multiple
instances of \fIrfile\fP [and -o \fIlfile\fP]. Does not expand wildcards, use
\fBmget\fR for that.
.PP
.Ds
get README
get README -o debian.README
get README README.mirrors
get README -o debian.README README.mirrors -o debian.mirrors
.De

.BR glob " \fIcommand patterns\fP"
.PP
Glob given patterns containing metacharacters and pass result to given command.
E.g. ``glob echo *''.

.B help
[\fIcmd\fP]
.PP
Print help for \fIcmd\fP or if no \fIcmd\fP was specified print a list of
available commands.

.B jobs
.RB [ -v ]
.PP
List running jobs. -v means verbose, several -v can be specified.

.B kill
all|\fIjob_no\fP
.PP
Delete specified job with \fIjob_no\fP or all jobs.  (For \fIjob_no\fP see
.BR jobs
)

.B lcd
\fIldir\fP
.PP
Change current local directory \fIldir\fP. The previous local
directory is stored as `-'. You can do `lcd -' to change the directory back.

.B lpwd
.PP
Print current working directory on local machine.

.B ls
\fIparams\fP
.PP
List remote files. You can redirect output of this command to file or
via pipe to external command.  By default, ls output is cached, to see
new listing use
.B rels
or
.B "cache flush."

.BR mget " [" -c "] [" -d "]"
.RB "[" -e "] \fIfiles\fP"
.PP
Gets selected files with expanded wildcards.
.PP
.Ds
   -c  continue, reget.
   -d  create directories the same as file names and get
       the files into them instead of current directory.
   -e  delete remote files after successful transfer
.De

.B mirror
.RI [ OPTS "] [" remote
.RI "[" local "]]"
.PP
Mirror specified remote directory to local directory.
.PP
.Ds
 -c, --continue         continue a mirror job if possible
 -e, --delete           delete files not present at remote site
 -s, --allow-suid       set suid/sgid bits according to remote site
 -n, --only-newer       download only newer files (-c won't work)
 -r, --no-recursion     don't go to subdirectories
 -p, --no-perms         don't set file permissions
     --no-umask         don't apply umask to file modes
 -R, --reverse          reverse mirror (put files)
 -L, --dereference      download symbolic links as files
 -N, --newer-than FILE  download only files newer than the file
 -i \fIRX\fP, --include \fIRX\fP    include matching files (only one allowed)
 -x \fIRX\fP, --exclude \fIRX\fP    exclude matching files (only one allowed)
 -t \fINx\fP, --time-prec \fINx\fP  set time precision to \fIN\fP seconds (\fIx\fP=s)
                        minutes (\fIx\fP=m) hours (\fIx\fP=h) or days (\fIx\fP=d)
 -v, --verbose          verbose operation
.De
.PP
When using -R, the first directory is local and the second is remote.
If the second directory is omitted, basename of first directory is used.
If both directories are omitted, current local and remote directories are used.
.PP
\fIRX\fP is an extended regular expression, just like in
.BR egrep (1).
.PP
Note that when -R is used (reverse mirror), symbolic links are not created
on server, because ftp protocol cannot do it. To upload files the links refer
to, use `mirror -RL' command (treat symbolic links as files).

.B mkdir
.RB "[" -p "] " \fIdir(s)\fP
.PP
Make remote directories. If -p is used, make all components of paths.

.B module 
.IR "module " [ " args " ]
.PP
Load given module using dlopen(3) function. If module name does not contain
a slash, it is searched in PKGLIBDIR, usually
.IR /usr/lib/lftp " or " /usr/local/lib/lftp.
Arguments are passed to module_init function. See README.modules for technical
details.

.B more
\fIfiles\fP
.PP
Same as `cat \fIfiles\fP | more'. if \fBPAGER\fP is set, it is used as filter.
(See also \fBcat\fR, \fBzcat\fR and \fBzmore\fR)

.B mput
.RB [ -c "] [" -d "] \fIfiles\fP
.PP
Upload files with wildcard expansion. -c means reput, -d means to
create remote directories and use the same remote name as local
one. By default it uses the basename of local name as remote one.

.B mrm
\fIfile(s)\fP
.PP
Removes specified file(s) with wildcard expansion.

.B mv
\fIfile1\fP \fIfile2\fP
.PP
Rename \fIfile1\fP to \fIfile2\fP.

.B nlist
[\fIargs\fP]
.PP
List remote file names

.B open
.RB [ -e " \fIcmd\fP]"
.BR "[" -u " \fIuser\fP[", "\fIpass\fP]]"
.BR "[" -p " \fIport\fP] \fIhost\fP|\fIurl\fP"
.PP
Select an ftp server.

.B pget
.RI [ OPTS "] " rfile " [" "\fB-o\fP lfile"
.RI ]

Gets the specified file using several connections. This can speed up
transfer, but loads the net heavily impacting other users. Use only if
you really have to transfer the file ASAP, or some other user may go
mad :) Options:

.Ds
 -n \fImaxconn\fP  set maximum number of connections (default 5)
 -u          try to recognize URLs
.De
.PP

.B put
.RB [ -c "] " \fIlfile\fP " [" -o
.RB \fIrfile\fP]
.PP
Upload \fIlfile\fP with remote name \fIrfile\fP. If -o omitted, the basename
of \fIlfile\fP is used as remote name. -c means reput, which requires you
to have permission to overwrite remote files in current
directory. Does not expand wildcards, use \fBmput\fR for that.

.B pwd
.PP
Print current remote directory.

.B queue
\fIcmd\fP
.PP
Add the given command to queue for sequential execution. Each site has its own
queue. Don't try to queue `cd' or `lcd' commands, it may confuse lftp. Instead
do the cd/lcd before `queue' command, and it will remember the place in which
the command is to be done.
.PP
.Ds
queue get one_file
cd a_directory
queue get another_file
.De

.B quote
\fIcmd\fP
.PP
Send the command uninterpreted. Use with caution - it can lead to
unknown remote state and thus will cause reconnect. You cannot
be sure that any change of remote state because of quoted command
is solid - it can be reset by reconnect at any time.

.BR "reget \fIrfile\fP " [ -o " \fIlfile\fP]"
.PP
Same as `get -c'.

.B rels
[\fIargs\fP]
.PP
Same as `ls', but ignores the cache.

.B renlist
[\fIargs\fP]
.PP
Same as `nlist', but ignores the cache.

.BR repeat " [\fIdelay\fP] [\fIcommand\fP]"
.PP
Repeat the command. Between the commands a delay inserted, by default 1 second.
Example:
.Ds
repeat at tomorrow -- mirror
repeat 1d mirror
.De

.BR reput " \fIlfile\fP [" -o " \fIrfile\fP]"
.PP
Same as `put -c'.

.BR rm " [" -r "]"
\fIfiles\fP
.PP
Remove remote files.  Does not expand wildcards, use \fBmrm\fR for
that. -r is for recursive directory remove. Be careful, if something goes
wrong you can lose files.

.B rmdir
\fIdir(s)\fP
.PP
Remove remote directories.

.B scache
[\fIsession\fP]
.PP
List cached sessions or switch to specified session.

.B set
[\fIvar\fP [\fIval\fP]]
.PP
Set variable to given value. If the value is omitted, unset the variable.
Variable name has format ``name/closure'', where closure can specify
exact application of the setting. See below for details.
If set is called with no variable then only altered settings are listed.
It can be changed by options:
.PP
.Ds
 -a  list all settings, including default values
 -d  list only default values, not necessary current ones
.De
.PP

.B site
\fIsite_cmd\fP
.PP
Execute site command \fIsite_cmd\fP and output the result.
You can redirect its output.

.BR sleep " \fIinterval\fP "
.PP
Sleep given time interval and exit. Interval is in seconds by default, but
can be suffixed with 'm', 'h', 'd' for minutes, hours and days respectively.
See also \fBat\fP.

.B source
\fIfile\fP
.PP
Execute commands recorded in file \fIfile\fP.

.B suspend
.PP
Stop lftp process. Note that transfers will be also stopped until you
continue the process with shell's fg or bg commands.

.B user
\fIuser\fP [\fIpass\fP]
.PP
Use specified info for remote login.

.B version
.PP
Print \fBlftp\fR version.

.B wait
[\fIjobno\fP]
.PP
Wait for specified job to terminate. If jobno is omitted, wait for last
backgrounded job.

.B zcat
\fIfiles\fP
.PP
Same as cat, but filter each file through zcat. (See also \fBcat\fR,
\fBmore\fR and \fBzmore\fR)

.B zmore
\fIfiles\fP
.PP
Same as more, but filter each file through zcat. (See also \fBcat\fR,
\fBzcat\fR and \fBmore\fR)

.PP
On startup, lftp executes
.IR "~/.lftprc " and " ~/.lftp/rc" "."
You can place aliases
and `set' commands there. Some people prefer to see full protocol
debug, use `debug' to turn the debug on.
.PP
There is also a system-wide startup file in
.IR /etc/lftp.conf .
It can be in different directory, see FILES section.
.PP
.B lftp
has the following settable variables (you can also use
`set -a' to see all variables and their values):
.TP
.BR bmk:save-passwords \ (bool)
save plain text passwords in ~/.lftp/bookmarks on `bookmark add' command.
Off by default.
.TP
.BR cmd:at-exit \ (string)
the commands in string are executed before lftp exits.
.TP
.BR cmd:csh-history \ (bool)
enables csh-like history expansion.
.TP
.BR cmd:fail-exit \ (bool)
if true, exit when an unconditional (without || and && at begin) command fails.
.TP
.BR cmd:long-running \ (seconds)
time of command execution, which is
considered as `long' and a beep is done before next prompt. 0
means off.
.TP
.BR cmd:ls-default \ (string)
default ls argument
.TP
.BR cmd:prompt \ (string)
The prompt. lftp recognizes the following backslash-escaped special
characters that are decoded as follows:

.RS
.PD 0
.TP
.B \e@
insert @ if current user is not default
.TP
.B \ea
an ASCII bell character (07)
.TP
.B \ee
an ASCII escape character (033)
.TP
.B \eh
the hostname you are connected to
.TP
.B \en
newline
.TP
.B \es
the name of the client (lftp)
.TP
.B \eu
the username of the user you are logged in as
.TP
.B \eU
the URL of the remote site (e.g., ftp://g437.ub.gu.se/home/james/src/lftp)
.TP
.B \ev
the version of \fBlftp\fP (e.g., 2.0.3)
.TP
.B \ew
the current working directory at the remote site
.TP
.B \eW
the basename of the current working directory at the remote site
.TP
.B \e\fInnn\fP
the character corresponding to the octal number \fInnn\fP
.TP
.B \e\e
a backslash
.TP
.B \e[
begin a sequence of non-printing characters, which could be used to
embed a terminal control sequence into the prompt
.TP
.B \e]
end a sequence of non-printing characters
.PD
.RE

.TP
.BR cmd:remote-completion \ (bool)
a boolean to control whether or not lftp uses remote completion.
.TP
.BR dns:SRV-query \ (bool)
query for SRV records and use them before gethostbyname. The SRV records
are only used if port is not explicitly specified. See RFC2052 for details.
.TP
.BR dns:cache-enable \ (bool)
enable DNS cache. If it is off, lftp resolves host name each time it reconnects.
.TP
.BR dns:cache-expire " (time interval)"
time to live for DNS cache entries. It has format <number><unit>+, e.g.
1d12h30m5s or just 36h. To disable expiration, set it to `inf' or `never'.
.TP
.BR dns:cache-size \ (number)
maximum number of DNS cache entries.
.TP
.BR dns:fatal-timeout \ (seconds)
limit the time for DNS queries. If DNS server is unavailable too long, lftp
will fail to resolve a given host name. 0 means unlimited, the default.
.TP
.BR dns:order " (list of protocol names)"
sets the order of DNS queries. Default is ``inet inet6'' which means first
look up address in inet family, then inet6 and use first matched.
.TP
.BR ftp:nop-interval \ (seconds)
delay between NOOP commands when downloading tail of a file. This is useful
for ftp servers which send "Transfer complete" message before flushing
data transfer. In such cases NOOP commands can prevent connection timeout.
.TP
.BR ftp:passive-mode \ (bool)
sets passive ftp mode. This can be useful if you are behind a firewall
or a dumb masquerading router.
.TP
.BR ftp:proxy \ (string)
specifies ftp proxy to use.
To disable proxy set this to empty string. Note that it is an ftp proxy which
uses ftp protocol, not ftp over http. Default value is taken from environment
variable \fBftp_proxy\fP if it starts with ``ftp://''.
.TP
.BR ftp:rest-list \ (bool)
allow usage of REST command before LIST command. This might be useful for
large directories, but some ftp servers silently ignore REST before LIST.
.TP
.BR ftp:skey-allow \ (bool)
allow sending skey/opie reply if server appears to support it. On by default.
.TP
.BR ftp:skey-force \ (bool)
do not send plain text password over the network, use skey/opie instead. If
skey/opie is not available, assume failed login. Off by default.
.TP
.BR ftp:sync-mode \ (bool)
if set lftp will send one command at a time and wait for
response. This might be useful if you are using a buggy ftp server or
router. When it is off, lftp sends a pack of commands and waits for
responses - it speeds up operation when round trip time is significant.
Unfortunately it does not work with all ftp servers and some routers have
troubles with it, so it is on by default.
.TP
.BR ftp:verify-address \ (bool)
verify that data connection comes from the network address of control
connection peer. This can possibly prevent data connection spoofing
which can lead to data corruption. Unfortunately, this can fail
for sertain ftp servers with several network interfaces,
when they do not set outgoing address on data socket, so it is disabled by default.
.TP
.BR ftp:verify-port \ (bool)
verify that data connection has port 20 (ftp-data) on its remote end.
This can possibly prevent data connection spoofing by users of remote
host. Unfortunately, too many windows and even unix ftp servers forget
to set proper port on data connection, thus this check is off by default.
.TP
.BR hftp:cache \ (bool)
allow server/proxy side caching for ftp-over-http protocol.
.TP
.BR hftp:proxy \ (string)
specifies http proxy for ftp-over-http protocol (hftp). The protocol hftp
cannot work without http proxy, obviously.
Default value is taken from environment
variable \fBftp_proxy\fP if it starts with ``http://'', otherwise from
environment variable \fBhttp_proxy\fP.
.TP
.BR http:cache \ (bool)
allow server/proxy side caching.
.TP
.BR http:proxy \ (string)
specifies http proxy. It is used when lftp works over http protocol.
Default value is taken from environment variable \fBhttp_proxy\fP.
.TP
.BR net:idle \ (seconds)
disconnect from server after that number of idle seconds.
.TP
.BR net:limit-rate \ (bytes " " per " " second)
limit transfer rate on data connection. 0 means unlimited.
.TP
.BR net:limit-max \ (bytes)
limit accumulating of unused limit-rate. 0 means unlimited.
.TP
.BR net:limit-total-rate \ (bytes " " per " " second)
limit transfer rate of all connections in sum. 0 means unlimited.
Note that sockets have receive buffers on them, this can lead to network
link load higher than this rate limit just after transfer beginning. You
can try to set net:socket-buffer to relatively small value to avoid this.
.TP
.BR net:limit-total-max \ (bytes)
limit accumulating of unused limit-total-rate. 0 means unlimited.
.TP
.BR net:max-retries \ (number)
the maximum number of sequential retries of an operation without success.
0 means unlimited.
.TP
.BR net:reconnect-interval \ (seconds)
sets the minimal time between reconnects.
.TP
.BR net:relookup-always \ (bool)
a boolean to control whether to lookup host address each time
before connecting or not. Can be useful if server uses dynamic ip
address and dynamic DNS. This setting is deprecated, use dns:cache-enable
instead.
.TP
.BR net:socket-buffer \ (bytes)
use given size for SO_SNDBUF and SO_RCVBUF socket options. 0 means system
default.
.TP
.BR net:socket-maxseg \ (bytes)
use given size for TCP_MAXSEG socket option. Not all operating systems support
this option, but linux does.
.TP
.BR net:timeout \ (seconds)
sets the network protocol timeout.
.TP
.BR xfer:clobber \ (bool)
if this setting is off, get commands will not overwrite existing
files and generate an error instead. Default is on.
.TP
.BR xfer:eta-terse \ (bool)
show terse ETA (only high order parts). Default is true.
.TP
.BR xfer:use-urls \ (bool)
recognize URLs by default in commands get, cat, mget, zcat, zmore.

.PP
The name of variables can be abbreviated unless it becomes
ambiguous. The prefix before `:' can be omitted too. You can
set one variable several times for different closures, and thus
you can get a particular settings for particular state. The closure
is to be specified after variable name separated with slash `/'.
.P

The closure for `dns:', `net:', `ftp:', `http:', `hftp:' domain variables
is currently just the host name as you specify it in the `open' command
(with some exceptions where closure is meaningless, e.g. dns:cache-size).
For other variables it is not currently used. See examples in the sample
.IR lftp.conf .

.P
Certain commands and settings take a time interval parameter. It has
the format Nx[Nx...], where N is time amount and x is time unit: d - days,
h - hours, m - minutes, s - seconds. Default unit is second. E.g. 5h30m.
Also the interval can be `infinity', `inf', `never', `forever' - it means
infinite interval. E.g. `sleep forever' or `set dns:cache-expire never'.

.P
.B Lftp
can speed up ftp operations by sending several commands at once and
then checking all the responses. See ftp:sync-mode variable. Sometimes
this does not work, thus synchronous mode is the default. You can try
to turn synchronous mode off and see if it works for you. It is known
that some network software dealing with address translation works
incorrectly in the case of several FTP commands in one network packet.

.PP
RFC959 says: ``The user-process sending another command before the
completion reply would be in violation of protocol; but server-FTP
processes should queue any commands that arrive while a preceding
command is in progress''. Also, RFC1123 says: ``Implementors MUST
NOT assume any correspondence between READ boundaries on the control
connection and the Telnet EOL sequences (CR LF).'' and ``a single READ
from the control connection may include more than one FTP command''.

So it must be safe to send several commands at once, which speeds up
operation a lot and seems to work with all Unix and VMS based ftp
servers. Unfortunately, windows based servers often cannot handle
several commands in one packet, and so cannot some broken routers.

.SH OPTIONS
.TP
.B \-d
Switch on debugging mode
.TP
.BI \-e " cmd"
Execute given command
.TP
.BI \-p " port"
Use the given port to connect
.TP
.BI \-u " user\fR[\fP\fB,\fPpass\fR]\fP"
Use the given username and password to connect
.TP
.BI \-f " script_file"
Execute commands in the file and exit
.TP
.BI \-c " commands"
Execute the given commands and exit

.SH ENVIRONMENT VARIABLES
The following environment variables are processed by \fBlftp\fR:
.IP "\fBHOME\fP"
Used for (local) tilde (`~') expansion
.IP "\fBSHELL\fP"
Used by the \fB!\fR command to determine the shell to run.
.IP "\fBPAGER\fP"
This should be the name of the pager to use.  It's used by the
\fBmore\fR and \fBzmore\fR commands.
.IP "\fBhttp_proxy\fP"
Used to set initial http:proxy and hftp:proxy variables.
.IP "\fBftp_proxy\fP"
Used to set initial ftp:proxy or hftp:proxy variables, depending
on URL protocol used in this environment variable.

.SH FILES
.TP
.I "/etc/lftp.conf"
system-wide startup file. Actual location depends on \-\-sysconfdir
configure option. It is \fI/etc\fR when prefix is \fI/usr\fR,
\fI/usr/local/etc\fR by default.

.TP
.I "~/.lftp/rc," "~/.lftprc"
These files are executed on lftp startup after \fI/etc/lftp.conf\fR.
.TP
.I "~/.lftp/log"
The file things are logged to when lftp moves into the background in
nohup mode.
.TP
.I "~/.lftp/bookmarks"
The file is used to store lftp's bookmarks.  See the \fBbookmark\fR
command.
.TP
.I "~/.lftp/cwd_history"
The file is used to store old working directories for each site visited.
.TP
.I "~/.netrc"
The file is consulted to get default login to ftp server.

.SH SEE ALSO
.BR ftpd "(8), " ftp (1)
.br 
RFC854 (telnet),
RFC959 (ftp),
RFC1123,
RFC1945 (http/1.0),
RFC2052 (SRV RR),
RFC2068 (http/1.1),
RFC2428 (ftp/ipv6).

.SH AUTHOR
.nf
Alexander V. Lukyanov
lav@yars.free.net
.fi

.SH ACKNOWLEDGMENTS
This manual page was originally written by Christoph Lameter
<clameter@debian.org>, for the Debian GNU/Linux system.
The page was improved by Nicolas Lichtmaier <nick@Feedback.com.ar>,
James Troup <J.J.Troup@comp.brad.ac.uk> and
Alexander V. Lukyanov <lav@yars.free.net>.
