#!/bin/sh

# lftpget - get a file with lftp
# Copyright (c) 1999 Alexander V. Lukyanov <lav@yars.free.net>
# This file is covered by GNU GPL. See file COPYING for details.

# $Id$

INTRO="set cmd:verbose y; set cmd:at-exit;"
SCRIPT=""

for f
do
   need_pass=false
   case "$f" in
   "*[\"\\]*")
      # need to quote
      f="`echo "$f" | sed 's/\([\\\"]\)/\\\1/g'`"
      ;;
   esac
   case "$f" in
   "*://*:*@*")  ;;
   "*://*@*")    need_pass=true;;
   esac

   if $need_pass; then
      SCRIPT="$SCRIPT echo \"$f\" needs password;"
   fi
   SCRIPT="$SCRIPT get -u \"$f\";"
done

if [ "$SCRIPT" = "" ]; then
   echo "Usage: $0 URL [URL...]" >&2
   exit 1
fi

exec lftp -c "$INTRO $SCRIPT"
