#ifdef WITH_MODULES
# define MODULE_PROTO_FTP  1
# define MODULE_PROTO_HTTP 1
# define MODULE_PROTO_FILE 1
# define MODULE_PROTO_FISH 1
# define MODULE_CMD_MIRROR 1
# define MODULE_CMD_SLEEP  1
#endif
